version: '3.8'

services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Opensearch38!
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 10s
      retries: 5

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    networks:
      - opensearch-net
    depends_on:
      opensearch-node1:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_HOST=opensearch-node1
      - OPENSEARCH_PORT=9200
      - PROJECT_NAME=${PROJECT_NAME:-default}
      - PROJECT_GOAL=${PROJECT_GOAL:-default}
      - DEBUG=true
      - MONITORING_INTERVAL=5.0
      - DOCKER_HELPER_IMAGE=alpine:latest
      - DOCKER_TIMEOUT=10
      - HOST_PROC=/host/proc  # Point to the host's proc filesystem
      - HOST_DEV=/host/dev    # Point to the host's dev filesystem
      - HOST_OS=macos         # Explicitly set the host OS type for better detection
      - DOCKER_HOST=${DOCKER_HOST:-unix:///var/run/docker.sock}  # Allow override via .env
      - DOCKER_API_VERSION=1.41
      - PYTHONUNBUFFERED=1    # For better logging
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for host access
      - /proc:/host/proc:ro    # Mount host's proc filesystem as read-only
      - /dev:/host/dev:ro      # Mount host's device filesystem as read-only
      - /var/run:/host/var/run:ro  # Mount run directory for socket access
      - /run:/host/run:ro      # Additional run directory on some systems
      - /etc/passwd:/host/etc/passwd:ro  # Mount passwd file for username lookup
      - /etc/group:/host/etc/group:ro    # Mount group file for group lookup
    privileged: true           # Required for accessing host resources
    pid: "host"                # Use host's PID namespace directly
    # Note: We can't use both network_mode and networks, so we prioritize OpenSearch access
    # network_mode: "host"     # Share the host's network namespace for better access
    networks:
      - opensearch-net
    depends_on:
      opensearch-node1:
        condition: service_healthy

volumes:
  opensearch-data:

networks:
  opensearch-net: